
/**************************************************************
 *	
 *	flute, 8 bit, 44100Hz,
 *	2 channel, 384045 bytes/channel
 *	Total Size: 2 * 384045 + 4 (header) = 768134 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Rahmaan\Desktop\flute.wav
 *	Time-stamp: Thu Jul 09 00:44:05 2009
 *	
 **************************************************************/

#ifndef __FLUTEH__
#define __FLUTEH__

#define FLUTEFREQ 44100
#define FLUTELEN 384045

extern const unsigned char flute[384045];
extern const unsigned char flute_c2[384045];

#endif /* __FLUTEH__ */
